# docker-compose file for frontend development
# do not use in production!
# https://www.grampsweb.org/dev-frontend/setup/

version: "3.8"

services:
  gramps-proxy:
    image: nginx
    container_name: gramps-proxy-dev
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5555:80"
  gramps-api:
    container_name: gramps-api-dev
    build:
      context: ./dev
      dockerfile: Dockerfile.api
  gramps-frontend:
    container_name: gramps-frontend-dev
    build:
      context: .
      dockerfile: ./dev/Dockerfile.frontend
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  gramps_users:
  gramps_db:
  node_modules:
